language: python

matrix:
  include:
    - os: linux
      language: python
      python: 3.5
    - os: osx
      language: objective-c
      python: 3.5

before_install:
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update ;fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install python3 ;fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then python3 -V ;fi

install: 
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then python setup.py build install ;fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then python3 setup.py build install;fi

script: 
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then python setup.py test ;fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then python3 setup.py test ;fi