language: python

matrix:
  include:
    - os: linux
      language: python
      python: 3.5
    - os: osx
      language: objective-c
      python: 3.5

before_install:
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update ;fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install python3 ;fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then python3 -V ;fi

install: 
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then python src/pybot.py -setup ;fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then python3 src/pybot.py -setup ;fi

script: 
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then python src/tests.py ;fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then python3 src/tests.py ;fi